development:
  adapter: postgresql
  encoding: unicode
  database: modelorails_development
  pool: 5
  username: seusuariopogres
  password: suasenhapostgres
  template: template0
  host: localhost
  port: 5432

test: &test
  adapter: postgresql
  encoding: unicode
  database: modelorails_test
  pool: 5
  username: seusuariopogres
  password: suasenhapostgres
  template: template0
  host: localhost
  port: 5432

staging:
  adapter: postgresql
  encoding: unicode
  database: modelorails_production
  pool: 5
  username: seusuariopogres
  password: suasenhapostgres
  template: template0
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: modelorails_production
  pool: 5
  username: seusuariopogres
  password: suasenhapostgres
  template: template0
  host: localhost
